export default (app) => {
  app.post(
    `/tenant/:tenantId/vor-ai/completions`,
    require('./vorAICompletions').default,
  );
  app.post(
    `/tenant/:tenantId/vor-ai/files`,
    require('./vorAIFiles').default,
  );
  app.post(
    `/tenant/:tenantId/vor-ai/fine-tunes`,
    require('./vorAIFineTunes').default,
  );
  app.post(
    `/tenant/:tenantId/vor-ai/status`,
    require('./vorAIStatus').default,
  );
  app.post(
    `/tenant/:tenantId/vor-ai/save`,
    require('./vorAISave').default,
  );
  app.get(
    `/tenant/:tenantId/vor-ai`,
    require('./vorAIFind').default,
  );
  app.post(
    `/tenant/:tenantId/vor-ai/completions-on-configurator`,
    require('./vorAICompletionsOnConfigurator').default,
  );
  app.post(
    '/tenant/:tenantId/vor-ai/get-text-from-word',
    require('./vorAIGetTextFromFile').default,
  );
  app.post(
    '/tenant/:tenantId/vor-ai/generate-answers',
    require('./vorAIGetWordFile').default,
  );
  app.post(
    '/tenant/:tenantId/vor-ai/submit-extractions',
    require('./vorAISubmitExtractions').default,
  );
};
