export default (app) => {
  app.post(
    `/tenant/:tenantId/highlight`,
    require('./highlightCreate').default,
  );
  app.put(
    `/tenant/:tenantId/highlight/:id`,
    require('./highlightUpdate').default,
  );
  app.put(
    `/tenant/:tenantId/highlight/:id/tags`,
    require('./highlightTags').default,
  );
  app.post(
    `/tenant/:tenantId/highlight/import`,
    require('./highlightImport').default,
  );
  app.post(
    `/tenant/:tenantId/highlight/quick`,
    require('./highlightQuick').default,
  );
  app.delete(
    `/tenant/:tenantId/highlight`,
    require('./highlightDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/highlight/autocomplete`,
    require('./highlightAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/highlight`,
    require('./highlightList').default,
  );
  app.get(
    `/tenant/:tenantId/highlight/file/:id`,
    require('./highlightFindByFile').default,
  );
  app.get(
    `/tenant/:tenantId/highlight/:id`,
    require('./highlightFind').default,
  );
};
