export default (app) => {
  app.post(
    `/tenant/:tenantId/program-template`,
    require('./programTemplateCreate').default,
  );
  app.put(
    `/tenant/:tenantId/program-template/:id`,
    require('./programTemplateUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/program-template/import`,
    require('./programTemplateImport').default,
  );
  app.delete(
    `/tenant/:tenantId/program-template`,
    require('./programTemplateDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/program-template/autocomplete`,
    require('./programTemplateAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/program-template`,
    require('./programTemplateList').default,
  );
  app.get(
    `/tenant/:tenantId/program-template/meta`,
    require('./programTemplateMetaList').default,
  );
  app.post(
    `/tenant/:tenantId/program-template/summarizing-from-requirements`,
    require('./programTemplateSummarizingFromRequirements')
      .default,
  );
  app.get(
    `/tenant/:tenantId/program-template/:id`,
    require('./programTemplateFind').default,
  );
};
