export default (app) => {
  app.post(
    `/tenant/:tenantId/user-group`,
    require('./userGroupCreate').default,
  );
  app.put(
    `/tenant/:tenantId/user-group/:id`,
    require('./userGroupUpdate').default,
  );
  app.put(
    `/tenant/:tenantId/user-group/:groupId/:userId`,
    require('./userGroupToggle').default,
  );
  app.put(
    `/tenant/:tenantId/user-group/assign/:groupId/:doAssign`,
    require('./userGroupToggles').default,
  );
  app.put(
    `/tenant/:tenantId/group-user/assign/:userId/:doAssign`,
    require('./groupUserToggles').default,
  );
  app.post(
    `/tenant/:tenantId/user-group/import`,
    require('./userGroupImport').default,
  );
  app.delete(
    `/tenant/:tenantId/user-group`,
    require('./userGroupDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/user-group/autocomplete`,
    require('./userGroupAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/user-group`,
    require('./userGroupList').default,
  );
  app.get(
    `/tenant/:tenantId/user-group/:id`,
    require('./userGroupFind').default,
  );
};
