export default (app) => {
  app.post(
    `/tenant/:tenantId/program-control`,
    require('./programControlCreate').default,
  );
  app.put(
    `/tenant/:tenantId/program-control/:id`,
    require('./programControlUpdate').default,
  );
  app.put(
    `/tenant/:tenantId/program-control/:id/add-tasks`,
    require('./programControlAddTasks').default,
  );
  app.put(
    `/tenant/:tenantId/program-control/:id/tags`,
    require('./programControlTags').default,
  );
  app.post(
    `/tenant/:tenantId/program-control/import`,
    require('./programControlImport').default,
  );
  app.delete(
    `/tenant/:tenantId/program-control`,
    require('./programControlDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/program-control/autocomplete`,
    require('./programControlAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/program-control`,
    require('./programControlList').default,
  );
  app.get(
    `/tenant/:tenantId/program-control/:id`,
    require('./programControlFind').default,
  );
};
